name: LeetCode Streak Alert

on:
  schedule:
    - cron: '30 16 * * *'  # 10:45 PM IST (5:15 PM UTC)
  workflow_dispatch:

jobs:
  check-streak:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run streak checker
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
      run: python streak_check.py
